hw1
petcheetos/java-course-tasks pull request #1
Opened 2023-10-08 16:18 UTC by petcheetos

2023-10-12 07:21 UTC, infomouse requested changes

2023-10-12 07:21 UTC, infomouse commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +    public static int countK(int num) {
countK(1112) возвращает 0.

2023-10-12 07:21 UTC, infomouse commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +        int countSteps = 0;
Вроде можно обойдись без этой переменной.

2023-10-12 07:21 UTC, infomouse commented on src/main/java/edu/hw1/task7/CircularShift.java
> +    public static int rotateRight(int n, int shift) {
rotateRight(Integer.MAX_VALUE, 0) возвращает -1.
Всегда надо делать тесты на граничные значения.

2023-10-12 21:55 UTC, petcheetos commented on src/main/java/edu/hw1/task1/VideoLength.java
> +        return minutes * SECONDS_IN_MINUTE + seconds;
Добавила проверку, также сделала валидацию с помощью matches и регулярных выражений. Но у меня была идея обернуть в try catch преобразование из строки в число, чтобы обработать ошибки, возникающие, если строка содержит что-то кроме цифр или когда число больше максимально возможного (проверка на переполнение при умножении осталась бы). Как лучше поступить?

2023-10-13 06:31 UTC, infomouse commented on src/main/java/edu/hw1/task1/VideoLength.java
> +        return minutes * SECONDS_IN_MINUTE + seconds;
В данной задачи можно и через try-catch. Проверку на переполнение тоже можно через исключение, используя функцию Math.multiplyExact().
В целом данный подход менее предпочтителен, если есть возможность быстро провалидировать входные данные. Плюс создание самого исключения довольно дорогая операция, само исключение занимает не мало место в памяти. И если мы его ловим и не пробрасываем дальше, то по сути мы создали лишний мусор для GC.

2023-10-13 16:20 UTC, petcheetos commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +    public static int countK(int num) {
![image](https://github.com/petcheetos/java-course-tasks/assets/114106870/775de7e3-fda8-4d1e-a23d-6ca0554f6ce3)
там в условии просто число строго больше 1000

2023-10-13 16:24 UTC, infomouse commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +    public static int countK(int num) {
Это весомый аргумент :) Можете игнорировать этот комментарий.

2023-10-13 16:50 UTC, petcheetos commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +    public static int countK(int num) {
так происходит, потому что разность чисел, состоящих из цифр числа num, получается меньше 1000, следовательно возвращается -1, которое в сумме с 1 дает 0. можно, например, изменить сигнатуру функции, добавив параметр _int countK(int num, boolean isFirstIteration)_, чтобы избежать такой ситуации?

2023-10-13 17:00 UTC, petcheetos commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +        int countSteps = 0;
ее значение же возвращается, когда разность двух чисел дает константу и при рекурсии ее значение увеличивается. мне кажется, без нее будет грустно(

2023-10-13 18:33 UTC, infomouse commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +        int countSteps = 0;
При рекурсии ее значение не передается. Внутри каждой функции своя область видимости. По сути вы всегда возвращаете 1, если разность двух чисел дает константу.

2023-10-13 18:45 UTC, petcheetos commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +        int countSteps = 0;
переделала

2023-10-13 18:54 UTC, infomouse commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +    public static int countK(int num) {
Публичная функция должна быть с сигнатурой из задания. Внутри вы можете сделать свою, которую вызывать рекурсивно. И она вполне себе может работать со всеми числами. В публичной же делаете валидацию и проверку исходного числа и запускаете внутреннюю.

2023-10-13 19:09 UTC, petcheetos commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +    public static int countK(int num) {
хорошо, исправлено

2023-10-13 19:22 UTC, infomouse requested changes

2023-10-13 19:22 UTC, infomouse commented on src/main/java/edu/hw1/task5/Palindrome.java
> +        return (newNum > NUMBER_BASE) ? isPalindromeDescendant(newNum) : false;
Вроде можно обойтись без тернарного оператора.

2023-10-13 19:22 UTC, infomouse commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +    public static int countK(int num) {
countK(6174) возвращает 1.

2023-10-13 19:23 UTC, infomouse commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +    private static int doCountK(int num, boolean isFirstIteration) {
Неиспользуемые параметры надо удалять.

2023-10-13 19:41 UTC, petcheetos commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +    public static int countK(int num) {
исправлено

2023-10-13 19:44 UTC, infomouse approved these changes

2023-10-13 19:44 UTC, infomouse commented on src/main/java/edu/hw1/task6/KaprekarConstant.java
> +        } else if (difference == KAPREKAR_CONST) {
Финальным штрихом можно убрать этот else.

2023-10-15 16:18 UTC, merged