project4
petcheetos/java-course-tasks pull request #12
Opened 2023-12-09 07:17 UTC by petcheetos

2023-12-14 10:09 UTC, nexen505 requested changes

2023-12-14 10:09 UTC, nexen505 commented on src/main/java/edu/project4/Main.java
> +            if (threads > 1) {
Косметика: создание `FractalFrame` из `if` можно вытащить, так как условие влияет лишь на выбор реализации `edu.project4.render.Renderer`.

2023-12-14 10:09 UTC, nexen505 commented on src/main/java/edu/project4/render/RenderedMultiThreads.java
> +    private void executeIterations(
Проблема: этот и следующий код дублируется с однопоточным рендерингом.

Предложение: провести рефакторинг, чтобы многопоточный рендеринг вызывал однопоточный.

2023-12-14 10:09 UTC, nexen505 commented on src/main/java/edu/project4/render/RenderedMultiThreads.java
> +        executorService.shutdown();
Проблема: метод не дожидается окончания запущенных задач.

Предложение: создавать и закрывать `ExecutorService` на уровне данного метода, а не класса целиком.

2023-12-14 10:09 UTC, nexen505 commented on src/main/java/edu/project4/render/RendererOneThread.java
> +    private Point getPointAffineTransformation(Coefficient coefficient, Point point) {
Предложение: сделать это методом класса `Point`.

2023-12-14 10:09 UTC, nexen505 commented on src/main/java/edu/project4/render/RendererOneThread.java
> +    private Point getRotatedPoint(Point point, double theta) {
Предложение: сделать это методом класса `Point`.

2023-12-14 10:09 UTC, nexen505 commented on src/main/java/edu/project4/render/RenderedMultiThreads.java
> +                        synchronized (pixel) {
Предложение: сделать это синхронизированным методом класса `Pixel`.

2023-12-14 12:38 UTC, petcheetos commented on src/main/java/edu/project4/Main.java
> +            if (threads > 1) {
исправлено

2023-12-14 12:38 UTC, petcheetos commented on src/main/java/edu/project4/render/RenderedMultiThreads.java
> +    private void executeIterations(
исправлено

2023-12-14 12:39 UTC, petcheetos commented on src/main/java/edu/project4/render/RenderedMultiThreads.java
> +        executorService.shutdown();
исправлено

2023-12-19 12:11 UTC, nexen505 requested changes

2023-12-19 12:11 UTC, nexen505 commented on src/main/java/edu/project4/render/RenderedMultiThreads.java
> +        executorService.shutdown();
Проблема: в случае ошибок выше пул не закроется.

Предложение: уйти от ручной остановки с ожиданием в сторону `try-with-resources`.

2023-12-20 07:06 UTC, nexen505 commented on src/main/java/edu/project4/render/RenderedMultiThreads.java
> +            executorService.awaitTermination(millisecondsToAwait, TimeUnit.MILLISECONDS);
Мысль: это бесполезно до остановки пула.

2023-12-20 07:06 UTC, nexen505 approved these changes

2024-01-07 08:11 UTC, merged