hw9
petcheetos/java-course-tasks pull request #13
Opened 2023-12-10 15:11 UTC by petcheetos

2023-12-12 08:52 UTC, nexen505 requested changes

2023-12-12 08:52 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +    private final BlockingQueue<Metric> metricsToCollect;
Проблема: эта очередь в некотором смысле дублирует очередь задач `executorService`.

Предложение: вместо этой очереди при добавлении статистики запускать в `executorService` задачу на ее вычисление.

2023-12-12 08:52 UTC, nexen505 commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +    public void stop() {
Проблема: такой метод не идиоматичен.

Предложение: заменить его на реализацию интерфейса `AutoCloseable`.

2023-12-12 08:52 UTC, nexen505 commented on src/main/java/edu/project2/solvers/ParallelDFSMazeSolver.java
> +        executorService.shutdown();
Проблема: метод не выполнится, если вдруг будут ошибки до, что не закроет ресурс.

Предложение: заменить на использование `try-with-resources`.

2023-12-12 08:52 UTC, nexen505 commented on src/main/java/edu/project2/solvers/ParallelDFSMazeSolver.java
> +                findPath(maze, new Maze.Coordinate(newRow, newCol), end, visited, path);
Предложение: подумать над таким алгоритм, чтобы вместо рекурсивного вызова осуществлялся запуск параллельной задачи.

2023-12-19 17:37 UTC, petcheetos commented on src/main/java/edu/hw9/task1/StatsCollector.java
> +    public void stop() {
исправлено

2023-12-20 07:02 UTC, nexen505 approved these changes

2023-12-20 07:07 UTC, merged