hw10
petcheetos/java-course-tasks pull request #14
Opened 2023-12-17 11:09 UTC by petcheetos

2023-12-18 13:18 UTC, nexen505 requested changes

2023-12-18 13:18 UTC, nexen505 commented on src/main/java/edu/hw10/task1/generators/BooleanGenerator.java
> +            generatedValue = true;
Проблема: при указании аннотации `@NotNull` пропадает рандомизация.

Предложение: сделать так, чтобы при аннотации генерировалось `true/false`, а без нее `true/false/null`.

2023-12-18 13:18 UTC, nexen505 commented on src/main/java/edu/hw10/task2/CacheProxy.java
> +class CacheProxy implements InvocationHandler {
Предложение: добавить изначальное чтение персистентного кэша при создании кэширующего прокси. Вероятно, это потребует использования сериализации.

2023-12-18 15:55 UTC, petcheetos commented on src/main/java/edu/hw10/task2/CacheProxy.java
> +class CacheProxy implements InvocationHandler {
добавлено

2023-12-19 11:32 UTC, nexen505 approved these changes

2023-12-19 16:24 UTC, merged